<?php

 use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_theme().
 */
function movie_directory_theme($existing, $type, $theme, $path)
{
    return [
        'movie-listing' => [
            'variables' => ['content' => NULL],
        ],
        'movie-card' => [
            'variables' => ['content' => NULL],
        ],
    ];
}
/**
 * Implements hook_preprocess_page().
 */
function movie_directory_preprocess_page(array &$variables) {
    $path_matcher = \Drupal::service('path.matcher');
    // Log the front page status for debugging.
    \Drupal::logger('movie_directory')->notice('isFrontPage: ' . var_export($path_matcher->isFrontPage(), TRUE));
    
    if ($path_matcher->isFrontPage()) {
      $variables['front_page_message'] = t('Welcome to the front page!');
    }
    else {
      $variables['front_page_message'] = '';
    }
  }
/**
* Implements hook_entity_base_field_info_alter().
*/
function movie_directory_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  // Check if the entity type is 'user' and the 'pass' field exists
  if ($entity_type->id() === 'user' && isset($fields['pass'])) {
    // Add the custom password policy constraint to the 'pass' field
    $fields['pass']->addConstraint('PasswordPolicyCustomConstraint');
  }
}