<?php

declare(strict_types=1);

/**
 * @file
 * Provides an actualities entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function content_entity_test_theme(): array {
  return [
    'actualities' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for actualities templates.
 *
 * Default template: actualities.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the actualities information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_actualities(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function content_entity_test_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish actualitiess.
      $storage = \Drupal::entityTypeManager()->getStorage('actualities');
      $actualities_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($actualities_ids) as $actualities) {
        $actualities->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize actualitiess.
      $storage = \Drupal::entityTypeManager()->getStorage('actualities');
      $actualities_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($actualities_ids) as $actualities) {
        $actualities->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function content_entity_test_user_predelete(UserInterface $account): void {
  // Delete actualitiess that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('actualities');
  $actualities_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($actualities_ids)
  );
  // Delete old revisions.
  $actualities_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($actualities_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
